### ISSUE TITLE
Freezing when auto-refreshing

### ISSUE THREAD

**Issue by lordvolvo** [vbguyny/ws4kp#53]
I'm having a recurring issue where the "loading" screen will hang up.  Sometimes the screen will indicate that it's loading the pages but the blue status bar isn't moving and all pages say LOADING;  other times the bar is moving; and other times one or more pages says FAILED.  This happens maybe every 12 hours or so...sometimes more often or less often.

I'm using WS4000 for a local cable TV channel and the software is wonderful, but it's embarrassing when this happens.  Thankfully I use Chrome Remote Desktop to monitor the PC it's running on and refresh it when needed.  The program is running on WIN 7 using Opera.

Manually refreshing the page usually solves the issue.  But is there a way for the software to auto-refresh to reduce this freezing issue?  I've tried browser plug-ins that auto-refresh pages, but it doesn't put WS4000 into full-screen mode.

Thanks!

Mike
Beavercreek Ohio
https://cityofbeavercreekohio.viebit.com/

**Comment by vbguyny** [comment]
Hello Mike!
Do you know if the issue happens if you load the site in Chrome instead of Opera?

**Comment by lordvolvo** [comment]
It happens in both browsers.  Even in Firefox. I haven't tried Edge or IE.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: VBGuyNY ***@***.***> Date: 4/28/21  11:14 PM  (GMT-05:00) To: vbguyny/ws4kp ***@***.***> Cc: lordvolvo ***@***.***>, Author ***@***.***> Subject: Re: [vbguyny/ws4kp] Freezing when auto-refreshing (#53) 
Hello Mike!
Do you know if the issue happens if you load the site in Chrome instead of Opera?

**Comment by vbguyny** [comment]
Ok, thanks.  I'll see what I can do.

**Comment by lordvolvo** [comment]
Thank you!Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: VBGuyNY ***@***.***> Date: 4/28/21  11:59 PM  (GMT-05:00) To: vbguyny/ws4kp ***@***.***> Cc: lordvolvo ***@***.***>, Author ***@***.***> Subject: Re: [vbguyny/ws4kp] Freezing when auto-refreshing (#53) 
Ok, thanks.  I'll see what I can do.

**Comment by vbguyny** [comment]
I implemented retry logic on the back-end if the resource is not able to be retrieved.  If this happens, it will wait 10 seconds and try again up to 3 times.  If I make the time out any shorter NOAA will block the IP (https://github.com/weather-gov/api/discussions/401#discussion-3342759).

I implemented a patch in the latest version that might fix the issue.  It should to the very least make the site load faster:
https://github.com/vbguyny/ws4kp/commit/b1fb952e8cc3971c57cd9e8998756bc9753b9489

Please download the latest version of the code and put into your server.

**Comment by vbguyny** [comment]
![Screenshot_20210429-210540](https://user-images.githubusercontent.com/871502/116636236-d27e1480-a92e-11eb-8db5-3381d0f78b39.png)

**Comment by lordvolvo** [comment]
Will do.  I'll test it for a few days and let you know.  Many thanks for the change.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: VBGuyNY ***@***.***> Date: 4/29/21  9:07 PM  (GMT-05:00) To: vbguyny/ws4kp ***@***.***> Cc: lordvolvo ***@***.***>, Author ***@***.***> Subject: Re: [vbguyny/ws4kp] Freezing when auto-refreshing (#53) 
Reopened #53.

**Comment by vbguyny** [comment]
Issue with the navigation buttons in full screen not disappearing after auto refresh.

**Comment by vbguyny** [comment]
Fixed issue here: https://github.com/vbguyny/ws4kp/issues/55

**Comment by lordvolvo** [comment]
Thanks for working on this issue.  I downloaded the entire code from the green link on this page - https://github.com/vbguyny/ws4kp - but I'm still having the navigation icons superimposed over the screens.  Was I supposed to do something different to incorporate the fix?Mike-----Original Message-----

**Comment by vbguyny** [comment]
Does it say version 1.61 when the weather loads?

**Comment by vbguyny** [comment]
Never mind, I see you are running the latest version.  I'm not able to duplicate the issue from Chrome on my Windows 10 PC. How are you accessing the site?
Also does the same issue happen if you hit my due instead? (https://battaglia.ddns.net/twc/)
![Screenshot_20210512-000735](https://user-images.githubusercontent.com/871502/117917354-e3c40b00-b2b6-11eb-92ab-7f5b7d24d09f.png)

**Comment by lordvolvo** [comment]
Yes.But the odd thing is I have a test PC of similar specs running the same version of the software.  But on the test PC, the nav icons are back on the bottom.  Both PCs have the same OS and use Chrome.  What could be different?Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: VBGuyNY ***@***.***> Date: 5/12/21  12:03 AM  (GMT-05:00) To: vbguyny/ws4kp ***@***.***> Cc: lordvolvo ***@***.***>, Author ***@***.***> Subject: Re: [vbguyny/ws4kp] Freezing when auto-refreshing (#53) 
Does it say version 1.61 when the weather loads?

**Comment by vbguyny** [comment]
Sounds like a caching issue. Please follow these instructions to clear the cache and then try hitting the site again: https://support.google.com/accounts/answer/32050?co=GENIE.Platform%3DDesktop&hl=en

**Comment by lordvolvo** [comment]
I cleared the cache.  But now in Chrome it won't load any data when I enter a zip code.It does work in Opera, but the nav icons are still superimposed over the screen.  And the Load screen shows v. 1.61Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: VBGuyNY ***@***.***> Date: 5/12/21  12:43 PM  (GMT-05:00) To: vbguyny/ws4kp ***@***.***> Cc: lordvolvo ***@***.***>, Author ***@***.***> Subject: Re: [vbguyny/ws4kp] Freezing when auto-refreshing (#53) 
Sounds like a caching issue. Please follow these instructions to clear the cache and then try hitting the site again: https://support.google.com/accounts/answer/32050?co=GENIE.Platform%3DDesktop&hl=en

**Comment by vbguyny** [comment]
I am going to need to you see if there are any errors in the web inspector in Chrome (press F12 > Console).  Please paste the errors here.

**Comment by lordvolvo** [comment]
Here's a screen-grab:-----Original Message-----

**Comment by vbguyny** [comment]
The image did not get attached to GitHub.  Could you please attach it directly to the issue?

Also I don't see the issue happening tonight:
![Screenshot_20210513-002805](https://user-images.githubusercontent.com/871502/118077949-2b17cd80-b383-11eb-9c40-67dbdd436b9b.png)

**Comment by lordvolvo** [comment]
Ok, I'll attach that screen grab in the Github thread when I get a chance.Right now I'm running ws4000 on Opera since it's not working on chrome.  Interesting how the nav icons aren't staying up on Opera.  Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: VBGuyNY ***@***.***> Date: 5/13/21  12:36 AM  (GMT-05:00) To: vbguyny/ws4kp ***@***.***> Cc: lordvolvo ***@***.***>, Author ***@***.***> Subject: Re: [vbguyny/ws4kp] Freezing when auto-refreshing (#53) 
The image did not get attached to GitHub.  Could you please attach it directly to the issue?
Also I don't see the issue happening tonight:

**Comment by lordvolvo** [comment]
Errors are now posted in the thread.-----Original Message-----
